# Generated by Django 3.1.4 on 2021-01-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210116_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
