# Generated by Django 3.1.4 on 2021-01-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioimage',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
        migrations.DeleteModel(
            name='PortfolioCategory',
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
